# Generated by Django 3.1.12 on 2021-07-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('canvas_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('module', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='canvas_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.CharField(choices=[('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('4D', '4D'), ('4E', '4E'), ('4F', '4F'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('5D', '5D'), ('5E', '5E'), ('5F', '5F'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('6D', '6D'), ('6E', '6E'), ('6F', '6F'), ('6G', '6G'), ('6H', '6H'), ('NA', 'N/A')], default='NA', max_length=5),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('canvas_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('satisfactory', models.BooleanField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.student')),
            ],
        ),
    ]
