# Generated by Django 3.1.12 on 2021-08-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210711_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.CharField(choices=[('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('4D', '4D'), ('4E', '4E'), ('4F', '4F'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('5D', '5D'), ('5E', '5E'), ('5F', '5F'), ('6A', '6th, Q1, AM'), ('6B', '6th, Q1, PM'), ('6C', '6th, Q2, AM'), ('6D', '6th, Q2, PM'), ('6E', '6th, Q3, AM'), ('6F', '6th, Q3, PM'), ('6G', '6th, Q4, AM'), ('6H', '6th, Q4, PM'), ('NA', 'N/A')], default='NA', max_length=5),
        ),
        migrations.CreateModel(
            name='EntryTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('seating_location', models.TextField()),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.student')),
            ],
        ),
    ]
