# Generated by Django 3.1.12 on 2021-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210807_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
