# Generated by Django 3.1.12 on 2021-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210818_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teambuildingquestion',
            name='grade',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='canvas_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
