# Generated by Django 3.1.14 on 2022-05-19 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20211224_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField()),
                ('artist', models.TextField(blank=True, null=True)),
                ('for_playlist', models.BooleanField()),
                ('investigated', models.BooleanField(default=False)),
                ('student', models.ForeignKey(default='dc74089', on_delete=django.db.models.deletion.SET_DEFAULT, to='classroom.student')),
            ],
        ),
    ]
