# Generated by Django 3.1.14 on 2022-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_musicsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitticket',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exitticket',
            name='learning_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exitticket',
            name='understanding',
            field=models.IntegerField(default=5),
        ),
    ]
