# Generated by Django 3.1.14 on 2022-07-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20220701_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.CharField(choices=[('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('4D', '4D'), ('4E', '4E'), ('4F', '4F'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('5D', '5D'), ('5E', '5E'), ('5F', '5F'), ('6A', '6 Q1 AM'), ('6B', '6 Q1 PM'), ('6C', '6 Q2 AM'), ('6D', '6 Q2 PM'), ('6E', '6 Q3 AM'), ('6F', '6 Q3 PM'), ('6G', '6 Q4 AM'), ('6H', '6 Q4 PM'), ('NA', 'N/A')], default='NA', max_length=5),
        ),
    ]
