# Generated by Django 3.1.14 on 2022-07-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20220727_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
