# Generated by Django 3.1.14 on 2022-12-24 22:20

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_artrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='artrequest',
            name='image_in',
            field=models.FileField(blank=True, null=True, upload_to=classroom.models.user_in_dir),
        ),
        migrations.AlterField(
            model_name='artrequest',
            name='extra_params',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='artrequest',
            name='state',
            field=models.IntegerField(choices=[(0, 'Submitted'), (2, 'Accepted'), (4, 'Up Next'), (6, 'Processing'), (8, 'Awaiting Moderation'), (10, 'Fulfilled'), (12, 'Cancelled')], default=0),
        ),
    ]
