# Generated by Django 3.1.14 on 2022-12-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20221224_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='artrequest',
            name='exemplar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
