# Generated by Django 3.1.14 on 2022-12-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_artrequest_exemplar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artrequest',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
