# Generated by Django 3.1.14 on 2023-01-23 13:36

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_artrequest_negative_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='artrequest',
            name='user_feature_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Selfie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=classroom.models.user_selfie_dir)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.student')),
            ],
        ),
    ]
