# Generated by Django 3.1.14 on 2023-03-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20230123_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artrequest',
            old_name='user_feature_photo',
            new_name='feature_photo',
        ),
    ]
