# Generated by Django 3.1.14 on 2023-12-12 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20230306_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfie',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selfie',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.CharField(choices=[('6AM', '6th AM'), ('6PM', '6th PM'), ('78AM', '1st Period'), ('78PM', '7th Period'), ('NA', 'N/A')], default='NA', max_length=5),
        ),
    ]
